version: "3.8"

services:

  ngrok_http:
    build:
      context: ngrok/
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
      - "53:53"
    links:
      - web
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/share/nginx/html

